name: "Build and Push"

on:
  workflow_dispatch:
    inputs:
      tags:
        description: "Extra Tags: comma,separated"
        required: false
  release:
    types: [published]

env:
  REGISTRY: "ghcr.io"

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - name: "Checkout"
        uses: actions/checkout@v5

      - name: "Setup Buildx"
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: "Docker Login"
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ vars.GHCR_USER }}
          password: ${{ secrets.GHCR_PASS }}

      - name: "Generate Tags"
        id: tags
        uses: cssnr/docker-tags-action@v1
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}
          tags: ${{ inputs.tags }}

      - name: "Build and Push"
        uses: docker/build-push-action@v4
        with:
          context: nginx
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.tags.outputs.tags }}
